fix: return name on uipooldataprovider
aave/protocol-v2 pull request #300
Opened 2022-07-15 16:23 UTC by sakulstra

2022-07-15 16:27 UTC, sakulstra commented on contracts/misc/UiPoolDataProviderV2V3.sol
> +        bytes32 name = IERC20DetailedBytes(reserveData.underlyingAsset).name();
only these 3 lines changed - the rest is linting with the `pritter:write` config in the repo. Seems like it was not linted before.

2022-07-18 07:10 UTC, kartojal requested changes

2022-07-18 07:10 UTC, kartojal commented on contracts/misc/UiPoolDataProviderV2V3.sol
> +            .getUserLastUpdated(user);
Hey @sakulstra! Could you check your prettier or linter? Some lines contains random spaces before the function names.

2022-07-18 07:11 UTC, kartojal approved these changes

2022-07-18 07:12 UTC, merged